---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - kb.tutorial.kb.io
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kb.tutorial.kb.io
  resources:
  - cronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - kb.tutorial.kb.io
  resources:
  - cronjobs/status
  verbs:
  - get
  - patch
  - update
